---
apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-hub-config
  namespace: default
data:
  db_endpoint: "financehub-dev-restore.cgdrbvkghjok.eu-west-1.rds.amazonaws.com"
  myenv: "dev"
  worker: "2"
  hub_source : "hub-dev"
  logging_json: "1"
