
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-hub-deployment
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 80
  selector:
    matchLabels:
      service: finance-hub
  template:
    metadata:
      labels:
        app: finance-hub
        service: finance-hub #labels for the pods e.g kubectl get pod -l "service in (http-server)"
    spec:
      containers:
      - name: finance-hub
        image: 797036517683.dkr.ecr.eu-west-1.amazonaws.com/finance-hub:IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 2Gi
        ports:
        - name: finance-hub
          containerPort: 8069
        livenessProbe:
          httpGet:
            path: /
            port: 8069
          initialDelaySeconds: 90
          timeoutSeconds: 30
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 8069
          initialDelaySeconds: 120
          timeoutSeconds: 45
          periodSeconds: 120
        env:
        - name: db_name
          valueFrom:
            secretKeyRef:
              name: finance-hub-secret
              value: finance-hub-postgresqldb-name   
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: finance-hub-secret
              value: finance-hub-postgresqldb-user
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: finance-hub-secret
              value: finance-hub-postgresqldb-password
        - name: db_endpoint
          valueFrom:
            configMapKeyRef:
              name: finance-hub-config
              key: db_endpoint
        - name: myenv
          valueFrom:
            configMapKeyRef:
              name: finance-hub-config
              key: myenv
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
