---
apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-hub-config
  namespace: default
data:
  db_endpoint: "finance-hub-prod-apps.cdvjmqj39m9u.eu-west-1.rds.amazonaws.com"
  myenv: "live"
  worker: "9"
  hub_source : "hub-live"
  logging_json: "1"
  enable_redis: "True"
  redis_port: "6379"
  redis_dbindex: "0"