
---

apiVersion: v1
kind: Service
metadata:
  name: finance-hub
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 500
spec:
  type: LoadBalancer
  selector:
    app: finance-hub
  ports:
  - name: finance-hub
    port: 80
    targetPort: finance-hub
